# Generated by Django 5.1.1 on 2025-12-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="phonenumber",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
