# Generated by Django 5.2.8 on 2025-12-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authethication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address_line",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
